
setting :
    is_simulation : false
    maintained_distance : [-1.5, -0.5, 1.20]
    maintained_distance_ : [0.0, 0.0, 1.2]
    regeneration_duration : 0.25
    lambda : 1
    
    # laser setting
    laser :
        resolution : 0.05
        count_threshold : 2
        laser_height_threshold : 0.5
        extra_height : 3.5
        cycle_duration : 0.1
    
    # camera setting
    camera :
        position : [0.15, -0.04, 0.08]
        orientation : [0.270596, 0.65328, 0.65328, 0.270596]
        cycle_duration : 0.009
        

# dynamic setting
dynamic :
    trajectory_degree : 6
    minimization_degree : 3
    max_velocity : 1.5
    max_acceleration : 1.5
    flight_velocity : 1.0
    flight_acceleration : 1.0

# map setting
map :
    resolution : 0.008
    safe_margin : 0.65
    boundary :
        lower_x : -40.0
        upper_x : 40.0
        lower_y : -40.0
        upper_y : 40.0
        lower_z : 0.0
        upper_z : 80.0
    wall :
        number : 5
        boundary_0 : [-800.0, 900.0, -280, 380, 3.0, 300.0]
        boundary_1 : [9.0, 900.0, -280, 380, 0.0, 300.0]
        boundary_2 : [-800.0, -8.0, -280, 380, 0.0, 300.0]
        boundary_3 : [-800.0, 900.0, -280, -2.8, 0.0, 300.0]
        boundary_4 : [-800.0, 900.0, 3.8, 380, 0.0, 300.0]
        _boundary_0 : [-8.0, 9.0, -3.0, 4.0, 3.0, 3.0]
        _boundary_1 : [9.0, 9.0, -3.0, 4.0, 0.0, 3.0]
        _boundary_2 : [-8.0, -8.0, -3.0, 4.0, 0.0, 3.0]
        _boundary_3 : [-8.0, 9.0, -3.0, -3.0, 0.0, 3.0]
        _boundary_4 : [-8.0, 9.0, 4.0, 4.0, 0.0, 3.0]

# estimation setting
estimation :
    reserved_duration : 7.0
    valid_size : 20
    trajectory_degree : 6
    observation_size : 40
    predition_time : 5
    lambda : 0.001
    vaild_lost_duration : 1.0


#
visualization :
    flag : y
    corridor:
        color_rbga : [0.1 0.0 0.7 0.1]
    map : 
        duration : 3.0
