
setting :
    is_simulation : false
    maintained_distance : [1.0, 1.0, 1.0]
    regeneration_duration : 0.25
    lambda : 10
    
    # laser setting
    laser :
        resolution : 0.05
        count_threshold : 2
        laser_height_threshold : 0.25
        extra_height : 3.5
        cycle_duration : 0.1
    
    # camera setting
    camera :
        position : [0.15, -0.04, 0.08]
        orientation : [0.270596, 0.65328, 0.65328, 0.270596]
        cycle_duration : 0.009
        

# dynamic setting
dynamic :
    trajectory_degree : 6
    minimization_degree : 3
    max_velocity : 3.0
    max_acceleration : 2.0
    flight_velocity : 1.0
    flight_acceleration : 1.0

# map setting
map :
    resolution : 0.008
    safe_margin : 0.0s
    boundary:
        lower_x : -40.0
        upper_x : 40.0
        lower_y : -40.0
        upper_y : 40.0
        lower_z : 0.0
        upper_z : 80.0

# estimation setting
estimation :
    reserved_duration : 5.0
    valid_size : 10
    trajectory_degree : 6
    observation_size : 40
    predition_time : 10
    lambda : 0.001
    vaild_lost_duration : 1.0


#
visualization :
    flag : y
    corridor:
        color_rbga : [0.1 0.0 0.7 0.1]
    map : 
        duration : 3.0
